apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: boc0pf71q-python
  janus-idp.io/tekton: boc0pf71q-python
  backstage.io/kubernetes-id: boc0pf71q-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: boc0pf71q-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
